highlighter: rouge
markdown: kramdown
baseurl: http://faisalhakim47.github.io/blog
url: http://faisalhakim47.github.io/blog
title: efbrain
email: faisalhakim47
author: Faisal Hakim
description: I write what you read.
paginate: 7
permalink: /:title
gems: [jekyll-paginate]
sass:
  style: compressed
  sass_dir: _sass