highlighter: rouge
markdown: kramdown
url: http://faisalhakim47.github.io
title: efbrain
email: faisalhakim47
author: Faisal Hakim
description: I write what you read.
paginate: 7
permalink: /blog/:title
gems: [jekyll-paginate]
sass:
  style: compressed
  sass_dir: _sass